#!/usr/bin/env node
// Compose the pure schema generator with package-owned adapters that require
// lifecycle or language-specific glue outside the generic emitter.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build as buildAdapters, loadTypes, isNullable, isStringEnum, enumTypeName, pascal } from "./generate.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const genDir = path.join(root, "generated");
const wasmManifest = "rust-wasm/Cargo.toml";
const generatedLibBlock = `[lib]\ncrate-type = ["cdylib", "rlib"]\n`;
const packagedLibBlock = `[lib]\npath = "../../src/rust-wasm-entry.rs"\ncrate-type = ["cdylib", "rlib"]\n`;
const banner = "AUTOGENERATED by src/generate-output.mjs — do not edit by hand; edit schema/ and regenerate.";

const dartKeywords = new Set([
  "abstract", "as", "assert", "async", "await", "base", "break", "case", "catch", "class", "const", "continue",
  "covariant", "default", "deferred", "do", "dynamic", "else", "enum", "export", "extends", "extension", "external",
  "factory", "false", "final", "finally", "for", "Function", "get", "hide", "if", "implements", "import", "in",
  "interface", "is", "late", "library", "mixin", "new", "null", "of", "on", "operator", "part", "required",
  "rethrow", "return", "sealed", "set", "show", "static", "super", "switch", "sync", "this", "throw", "true",
  "try", "typedef", "var", "void", "when", "while", "with", "yield",
]);

function refName(schema) { return schema?.$ref?.split("/").pop() ?? null; }
function nonNullSchema(schema) {
  if (!isNullable(schema)) return schema;
  const types = schema.type.filter((type) => type !== "null");
  return { ...schema, type: types.length === 1 ? types[0] : types };
}
function lowerCamel(value) {
  const words = value.split(/[_\-\s]+/).filter(Boolean);
  const result = words.map((word, index) => index === 0 ? word[0].toLowerCase() + word.slice(1) : word[0].toUpperCase() + word.slice(1)).join("");
  const safe = /^\d/.test(result) ? `v${result}` : result;
  return dartKeywords.has(safe) ? `${safe}Value` : safe;
}
function dartType(schema) {
  schema = nonNullSchema(schema);
  const ref = refName(schema); if (ref) return ref;
  switch (schema?.type) {
    case "string": return "String";
    case "integer": return "int";
    case "number": return "double";
    case "boolean": return "bool";
    case "array": return `List<${dartType(schema.items || {})}>`;
    default: return "Map<String, Object?>";
  }
}
function enumValues(types) {
  const enums = new Map();
  for (const type of types) for (const property of type.props) if (isStringEnum(property.schema)) enums.set(enumTypeName(type.name, property.name), nonNullSchema(property.schema).enum);
  return enums;
}
function dartDecode(schema, expression, enumName = null) {
  const nullable = isNullable(schema); const inner = nonNullSchema(schema); const ref = refName(inner); let value;
  if (enumName) value = `${enumName}Wire.parse(${expression} as String)`;
  else if (ref) value = `${ref}.fromJson((${expression} as Map).cast<String, Object?>())`;
  else switch (inner?.type) {
    case "string": value = `${expression} as String`; break;
    case "integer": value = `${expression} as int`; break;
    case "number": value = `(${expression} as num).toDouble()`; break;
    case "boolean": value = `${expression} as bool`; break;
    case "array": {
      const itemRef = refName(inner.items);
      value = itemRef ? `(${expression} as List).map((value) => ${itemRef}.fromJson((value as Map).cast<String, Object?>())).toList(growable: false)` : `(${expression} as List).cast<${dartType(inner.items || {})}>()`;
      break;
    }
    default: value = `(${expression} as Map).cast<String, Object?>()`;
  }
  return nullable ? `${expression} == null ? null : ${value}` : value;
}
function dartEncode(schema, expression, enumName = null) {
  const inner = nonNullSchema(schema); const ref = refName(inner);
  if (enumName) return `${expression}.wireValue`;
  if (ref) return `${expression}.toJson()`;
  if (inner?.type === "array" && refName(inner.items)) return `${expression}.map((value) => value.toJson()).toList(growable: false)`;
  return expression;
}
function emitDart(types) {
  const output = [`// ${banner}`, ""];
  for (const [name, values] of enumValues(types)) {
    output.push(`enum ${name} {`); for (const value of values) output.push(`  ${lowerCamel(value)},`);
    output.push("}", "", `extension ${name}Wire on ${name} {`, "  String get wireValue => switch (this) {");
    for (const value of values) output.push(`    ${name}.${lowerCamel(value)} => '${value}',`);
    output.push("  };", "", `  static ${name} parse(String value) => switch (value) {`);
    for (const value of values) output.push(`    '${value}' => ${name}.${lowerCamel(value)},`);
    output.push(`    _ => throw FormatException('unknown ${name} value'),`, "  };", "}", "");
  }
  for (const type of types) {
    output.push(`final class ${type.name} {`, `  const ${type.name}({`);
    for (const property of type.props) output.push(`    ${property.required ? "required " : ""}this.${lowerCamel(property.name)},`);
    output.push("  });", "");
    for (const property of type.props) {
      const enumName = isStringEnum(property.schema) ? enumTypeName(type.name, property.name) : null;
      const typeName = enumName || dartType(property.schema); const nullable = !property.required || isNullable(property.schema);
      output.push(`  final ${typeName}${nullable ? "?" : ""} ${lowerCamel(property.name)};`);
    }
    output.push("", `  factory ${type.name}.fromJson(Map<String, Object?> json) => ${type.name}(`);
    for (const property of type.props) {
      const identifier = lowerCamel(property.name); const enumName = isStringEnum(property.schema) ? enumTypeName(type.name, property.name) : null; const expression = `json['${property.name}']`;
      output.push(property.required ? `        ${identifier}: ${dartDecode(property.schema, expression, enumName)},` : `        ${identifier}: ${expression} == null ? null : ${dartDecode(property.schema, expression, enumName)},`);
    }
    output.push("      );", "", "  Map<String, Object?> toJson() => {");
    for (const property of type.props) {
      const identifier = lowerCamel(property.name); const enumName = isStringEnum(property.schema) ? enumTypeName(type.name, property.name) : null; const source = property.required ? identifier : `${identifier}!`; const encoded = dartEncode(property.schema, source, enumName);
      output.push(property.required ? `        '${property.name}': ${encoded},` : `        if (${identifier} != null) '${property.name}': ${encoded},`);
    }
    output.push("      };", "}", "");
  }
  return {
    "dart/lib/canonical_interfaces.dart": output.join("\n"),
    "dart/pubspec.yaml": `name: canonical_interfaces\ndescription: Generated typed payloads for the canonical.plus API.\nversion: 0.1.0\npublish_to: none\nenvironment:\n  sdk: '>=3.8.0 <4.0.0'\n`,
  };
}

export function build() {
  const files = buildAdapters();
  const manifest = files[wasmManifest];
  if (typeof manifest !== "string" || !manifest.includes(generatedLibBlock)) throw new Error("generated Rust/WASM manifest no longer has the expected [lib] block");
  if (manifest.includes("rust-wasm-entry.rs")) throw new Error("generated Rust/WASM manifest already owns the package entrypoint");
  files[wasmManifest] = manifest.replace(generatedLibBlock, packagedLibBlock);
  Object.assign(files, emitDart(loadTypes()));
  return files;
}
export { loadTypes };
function main() {
  const check = process.argv.includes("--check"); let files;
  try { files = build(); } catch (error) { console.error(`error: ${error instanceof Error ? error.message : String(error)}`); process.exit(2); }
  let drift = 0;
  for (const [relativePath, content] of Object.entries(files)) {
    const absolutePath = path.join(genDir, relativePath);
    if (check) {
      const current = fs.existsSync(absolutePath) ? fs.readFileSync(absolutePath, "utf8") : null;
      if (current !== content) { console.error(`drift: ${relativePath}`); drift += 1; }
    } else { fs.mkdirSync(path.dirname(absolutePath), { recursive: true }); fs.writeFileSync(absolutePath, content); console.log(`wrote ${relativePath}`); }
  }
  if (check && drift > 0) { console.error(`${drift} file(s) out of date — run: npm run generate`); process.exit(1); }
  if (check) console.log("generated files up to date");
}
const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) main();
